name: wallet_connect
description: Dart implementation of WalletConnect Protocol.
version: 1.0.0
#homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  web_socket_channel: ^2.1.0
  pointycastle: ^3.1.1 
  uuid: ^3.0.4
